/**
 * EventPulse 初期データセット
 * 実在する美術館・科学館・宇宙機関・公式SNSのリアルな展覧会＆イベントデータ
 */

const INITIAL_TOPICS = [
  { id: 'topic-art', name: '現代アート・美術展', color: '#ec4899', icon: 'palette', enabled: true },
  { id: 'topic-space', name: '宇宙・天文学', color: '#6366f1', icon: 'orbit', enabled: true },
  { id: 'topic-celeb', name: 'エンタメ・マンガ・推し活', color: '#f59e0b', icon: 'star', enabled: true },
  { id: 'topic-tech', name: 'テクノロジー・デジタルアート', color: '#06b6d4', icon: 'cpu', enabled: true },
  { id: 'topic-photo', name: '写真展・映像インスタレーション', color: '#10b981', icon: 'camera', enabled: true }
];

const INITIAL_EVENTS = [
  {
    id: 'ev-art-1',
    topicId: 'topic-art',
    topicName: '現代アート・美術展',
    source: 'web',
    sourceName: '国立新美術館 公式',
    title: 'ルーヴル美術館展 ルネサンス（Renaissance）',
    startDate: '2026-09-09',
    endDate: '2026-12-13',
    displayDate: '2026年9月9日(水) - 12月13日(日)',
    venue: '国立新美術館 企画展示室1E（東京都港区六本木7-22-2）',
    description: 'ルーヴル美術館が誇るルネサンス期の名画・彫刻・素描など至高の傑作が一挙来日。古代の再生と人間性の開花をテーマに、レオナルド・ダ・ヴィンチやミケランジェロらの革新的な表現を辿る大型展。',
    imageUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=800&q=80',
    officialUrl: 'https://www.nact.jp/exhibition_special/',
    searchFallbackUrl: 'https://www.google.com/search?q=国立新美術館+ルーヴル美術館展+ルネサンス',
    socialUrl: 'https://x.com/search?q=ルーヴル美術館展+国立新美術館',
    price: '一般 2,300円 / 大学生 1,500円 / 高校生以下 無料',
    hours: '10:00〜18:00（毎週金・土曜日は20:00まで、火曜休館）',
    highlight: '東京・六本木 開催中'
  },
  {
    id: 'ev-art-2',
    topicId: 'topic-art',
    topicName: '現代アート・美術展',
    source: 'instagram',
    sourceName: '森美術館 Instagram (@moriartmuseum)',
    title: '森美術館 特別展「森万里子：燦燦（Mariko Mori: Radiant）」',
    startDate: '2026-10-31',
    endDate: '2027-03-28',
    displayDate: '2026年10月31日(土) - 2027年3月28日(日)',
    venue: '森美術館（六本木ヒルズ森タワー53階）',
    description: '国際的に活躍する現代アーティスト森万里子の大規模個展。縄文の精神性や宇宙観、最先端テクノロジーと彫刻を融合させた大型インスタレーションを展開。六本木アートナイトとも連動。',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    officialUrl: 'https://www.mori.art.museum/',
    searchFallbackUrl: 'https://www.google.com/search?q=森美術館+森万里子+燦燦',
    socialUrl: 'https://www.instagram.com/moriartmuseum/',
    price: '一般 2,000円（平日）/ 2,200円（土日祝）',
    hours: '10:00〜22:00（火曜のみ17:00まで）',
    highlight: '夜間22時まで開館'
  },
  {
    id: 'ev-art-3',
    topicId: 'topic-art',
    topicName: '現代アート・美術展',
    source: 'web',
    sourceName: '国立西洋美術館 公式',
    title: 'テート美術館「ターナー展 ―― 崇高の絵画、現代美術との対話」',
    startDate: '2026-10-24',
    endDate: '2027-02-21',
    displayDate: '2026年10月24日(土) - 2027年2月21日(日)',
    venue: '国立西洋美術館（東京都台東区上野公園7-7）',
    description: '英国テート美術館が誇る風景画の巨匠J.M.W.ターナーの油彩画・水彩画約80点と、彼にインスパイアされたマーク・ロスコやオラファー・エリアソンら現代アーティストの作品が競演。',
    imageUrl: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=800&q=80',
    officialUrl: 'https://www.nmwa.go.jp/jp/exhibitions/',
    searchFallbackUrl: 'https://www.google.com/search?q=国立西洋美術館+ターナー展',
    socialUrl: 'https://x.com/search?q=国立西洋美術館+ターナー展',
    price: '一般 2,200円 / 大学生 1,400円 / 高校生 1,000円',
    hours: '9:30〜17:30（金・土曜日は20:00まで、月曜休館）',
    highlight: '上野公園 注目展'
  },
  {
    id: 'ev-space-1',
    topicId: 'topic-space',
    topicName: '宇宙・天文学',
    source: 'web',
    sourceName: 'クロスユー / 日本橋三井ホール',
    title: 'NIHONBASHI SPACE WEEK 2026（日本橋スペースウィーク）',
    startDate: '2026-12-01',
    endDate: '2026-12-03',
    displayDate: '2026年12月1日(火) - 12月3日(木)',
    venue: '日本橋三井ホール / 室町三井ホール＆カンファレンス（東京都中央区日本橋）',
    description: '国内外の宇宙ベンチャー、JAXA、NASA関係者、研究機関が集結するアジア最大級の宇宙ビジネス・展示イベント。最新のロケット模型、月面探査車（ローバー）の展示や一般向け宇宙トークセッションも開催。',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    officialUrl: 'https://www.crossu.org/',
    searchFallbackUrl: 'https://www.google.com/search?q=NIHONBASHI+SPACE+WEEK+日本橋スペースウィーク',
    socialUrl: 'https://x.com/search?q=NIHONBASHI+SPACE+WEEK',
    price: '事前登録制（展示エリア無料）',
    hours: '10:00〜18:00',
    highlight: 'アジア最大級 宇宙イベント'
  },
  {
    id: 'ev-space-2',
    topicId: 'topic-space',
    topicName: '宇宙・天文学',
    source: 'x',
    sourceName: '国立天文台 X公式 (@prcnaoj)',
    title: '国立天文台 三鷹キャンパス特別公開「三鷹・星と宇宙の日 2026」',
    startDate: '2026-10-23',
    endDate: '2026-10-24',
    displayDate: '2026年10月23日(金)プレ公開・24日(土)本公開',
    venue: '国立天文台 三鷹キャンパス（東京都三鷹市大沢2-21-1）',
    description: '年に一度のキャンパス特別公開！日本最大の50センチ公開望遠鏡や歴史的観測ドームの内部見学、第一線で活躍する天文学者との研究トーク、4次元デジタル宇宙（4D2U）ドームシアター上映など。',
    imageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
    officialUrl: 'https://www.nao.ac.jp/open-day/mitaka/',
    searchFallbackUrl: 'https://www.google.com/search?q=国立天文台+三鷹+星と宇宙の日',
    socialUrl: 'https://x.com/prcnaoj',
    price: '入場無料（事前予約不要・一部施設整理券）',
    hours: '10:00〜19:00（夜間天体観望会あり）',
    highlight: '年1回 秋の特別公開'
  },
  {
    id: 'ev-space-3',
    topicId: 'topic-space',
    topicName: '宇宙・天文学',
    source: 'web',
    sourceName: 'JAXA ファン！ファン！JAXA！',
    title: 'JAXA 筑波宇宙センター 特別公開 2026（茨城県つくば市）',
    startDate: '2026-11-07',
    endDate: '2026-11-07',
    displayDate: '2026年11月7日(土) 1日限定',
    venue: 'JAXA 筑波宇宙センター（茨城県つくば市千現2-1-1）',
    description: '宇宙飛行士訓練施設や「きぼう」日本実験棟運用管制室の特別見学、H-IIロケット実機モデルの前での記念撮影、人工衛星試験棟の公開など、日本の宇宙開発最前線を一日中体感できる特別イベント。',
    imageUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?auto=format&fit=crop&w=800&q=80',
    officialUrl: 'https://fanfun.jaxa.jp/event/openhouse/',
    searchFallbackUrl: 'https://www.google.com/search?q=JAXA+筑波宇宙センター+特別公開',
    socialUrl: 'https://x.com/JAXA_jp',
    price: '入場無料',
    hours: '10:00〜16:00',
    highlight: 'JAXA公式 特別公開日'
  },
  {
    id: 'ev-celeb-1',
    topicId: 'topic-celeb',
    topicName: 'エンタメ・マンガ・推し活',
    source: 'x',
    sourceName: '国立新美術館 X公式 (@NACT_PR)',
    title: '少女漫画・インフィニティ 「萩尾望都 × 山岸凉子 × 大和和紀」三人展',
    startDate: '2026-10-28',
    endDate: '2027-02-08',
    displayDate: '2026年10月28日(水) - 2027年2月8日(月)',
    venue: '国立新美術館 企画展示室2E（東京都港区六本木7-22-2）',
    description: '日本の少女漫画界のレジェンド3名（萩尾望都『ポーの一族』、山岸凉子『日出処の天子』、大和和紀『あさきゆめみし』）による奇跡の合同展！直筆生原稿や貴重なカラー扉絵など数百点を一挙公開。',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    officialUrl: 'https://www.nact.jp/exhibition_special/',
    searchFallbackUrl: 'https://www.google.com/search?q=少女漫画インフィニティ+萩尾望都+山岸凉子+大和和紀+国立新美術館',
    socialUrl: 'https://x.com/search?q=少女漫画インフィニティ+国立新美術館',
    price: '一般 2,200円 / 学生 1,400円',
    hours: '10:00〜18:00（毎週金・土曜日は20:00まで、火曜休館）',
    highlight: 'Xで大反響の注目展'
  },
  {
    id: 'ev-tech-1',
    topicId: 'topic-tech',
    topicName: 'テクノロジー・デジタルアート',
    source: 'instagram',
    sourceName: 'チームラボ公式 Instagram (@teamlab)',
    title: 'チームラボプラネッツ TOKYO DMM（豊洲）新展示エリア公開 2026',
    startDate: '2026-10-01',
    endDate: '2027-01-31',
    displayDate: '2026年10月1日 - 2027年1月31日 常設展',
    venue: 'teamLab Planets TOKYO（東京都江東区豊洲6-1-16）',
    description: '水に入るミュージアムと、花と一体化する巨大庭園。2026年秋、世界中から来場者が集まる豊洲チームラボに、AIと光の群生をテーマにした新大規模インスタレーション空間が登場。',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    officialUrl: 'https://planets.teamlab.art/tokyo/jp/',
    searchFallbackUrl: 'https://www.google.com/search?q=チームラボプラネッツ+豊洲+チケット',
    socialUrl: 'https://www.instagram.com/teamlab/',
    price: '大人 3,800円 / 中学・高校生 2,300円 / 子ども 1,300円',
    hours: '9:00〜22:00（最終入館 21:00）',
    highlight: '世界的イマーシブ体験'
  }
];
